### ISSUE TITLE
Libertinus build error

### ISSUE THREAD

**Issue by ivo-s** [theleagueof/fontship#127]
Github workflow pulls the newest Fontship and that causes an error even with commits where there was none before (I checked). There seems to be a Python module `unidecode` missing somewhere.
https://github.com/ivo-s/libertinus/runs/1671895283

I am just guessing this is a FontShip bug, because I didn't find any package configuration in the Libertinus workflow file.

**Comment by alerque** [comment]
Thanks for this report. I'm pretty sure this is an Arch Linux packaging bug with Python modules that got updated without catching dependency changes, but try to chase it down and we can I'll keep this open to track confirming that it gets fixed for Fontship Docker builds.

The fact that this shows up at all is a side effect of the out-of-sync release [mentioned here](https://github.com/alerque/libertinus/issues/418#issuecomment-754891317) where *latest* is not actually the same as *v0.7.2*, it doesn't have quite the same version of dependencies baked in, and it didn't get the same testing at build time.

**Comment by alerque** [comment]
Confirmed my hunch, this is related to `gftools`. In fact it's not even an Arch package issue so much as a straight up gftools bug, their requirements.txt file is completely out of sync with what it actually needs to run the refactored latest releases. I've [submitted a fix upstream](https://github.com/googlefonts/gftools/pull/289) but I'll also monkey patch the Arch packaging ahead of time to get this fixed for Fontship CI runs.
