### ISSUE TITLE
Re-accept developer agreement

### ISSUE THREAD

**Issue by alerque** [theleagueof/fontship#138]
Hey @micahbrich I think GitHub changed something in their developer agreement and you need to accept the terms on behalf of theleagueof org again:

From this project, Releases tab, click to edit one of the existing releases. The top of the form is "Publish this release" but for me has a warning that an admin needs to accept the agreement first.

This has been outstanding [for a couple months now](https://gitter.im/theleagueof/tooling?at=60164d1d428d9727dd45c181) but I just pushed a release through last night no it matters a bit right now that it shows up in the right places.

**Comment by micahbrich** [comment]
Shoot @alerque I'm sorry I missed this — I need to research some way to get notifications about this stuff, I'm not sure why I never do. 

But I just did it, so hopefully smooth sailing now! 🙏
