### ISSUE TITLE
Update manifest on GH Action Marketplace  / Re accept the dev agreement

### ISSUE THREAD

**Issue by alerque** [theleagueof/fontship#147]
Hey @micahbrich this one is for you. This repo is published as a GH Action, and at some point I had you accept the license agreement with GH so we could get it there. Well it is still published, but I can't *update* the action flow because it says something isn't agreed to. I would assume GH just changed their terms a bit and need new signoffs. I don't know where the TOS is going to be, but the blocked I see can be seen by opening the current release, clicking edit, and seeing this in the header: 

![image](https://github.com/user-attachments/assets/c464d92a-8552-4f64-933a-d6f8966fbd9c)

Can you square that away so I can update the action manifest so it can accept arguments in a more flexible way?

**Comment by micahbrich** [comment]
Boom! Hard to find but I think we should be good to go 🙏  Thanks Calebbbbbbbbbb

<img width="1041" alt="Screenshot 2024-09-21 at 11 14 21 AM" src="https://github.com/user-attachments/assets/63128ca1-aa4f-4588-bfe9-b9c9ba6227ed">
