### ISSUE TITLE
Design a logo

### ISSUE THREAD

**Issue by alerque** [theleagueof/fontship#31]
How are we supposed to pitch a tool **to designer types** if it doesn't even have a shinny logo?

Unfortunately I'm that long-bearded programmer dude who lives in a terminal (yes, I am in fact composing this very issue in `vim`!). Somebody else is going to have to take this one on. Does anybody want to give back to @theleagueof for all the free fonts by contributing some cool branding for this project?

**Comment by sprngr** [comment]
Hi there, long time League font user and fellow long-bearded programmer. I was looking at fonts and saw this was flagged with `help wanted`. Since I'm somewhat handy with vectors and want to contribute in someway, I took an attempt at a logo for this neat project. It makes use of [Fanwood](https://github.com/theleagueof/fanwood).

![fontship](https://user-images.githubusercontent.com/29021/87745041-ea7b1200-c7ba-11ea-8345-b71a22ca2b6e.png)

Hopefully you may like it or at least derive some inspiration toward a better logo for the project.

Cheers!

**Comment by alerque** [comment]
Thanks for starting the ball rolling @sprngr. I appreciate the contribution and I do actually kind of like the concept. I have a concern however that it's too close to the concept art used by Docker:

![image](https://user-images.githubusercontent.com/173595/90153372-90597680-dd91-11ea-9c12-022c7ecb2c4f.png)

This is more than a theoretical conflict because I expect use as a Docker container will be one of the main ways many designers opt to use it, installing a bunch of native dependencies being a bit more of a a fiasco. Since Fontship appears in both Docker Hub's container registry and Github's own container packages registry and as a CI Action that supports Docker usage is also marked with the Docker icon, it seems like this might be a perpetual source for confusion.

Thoughts?

Also one more think to consider when evaluating designs for this is the most commonly seen format we're going to have is probably going to be a square aspect ratio. To make matters worse Github Actions has been cropping square aspect ratio icons into circles for display. Ugg ... in short we don't have much icon space to work with. We'll probably want a nice full logo to put in the Readme / documentation and a simplified essence version for icons.

**Comment by sprngr** [comment]
I 100% get that concern, funnily enough my idea for the logo is based off a container ship design. Totally don't want to cause any sort of confusion. It's good to get the ball rolling and find out what doesn't work.

As for aspect ratios, that is also a good limitation to know. I can try to get some thoughts put together that can fit in a square or bet turned into a circle if needed.

Does making use of a literal ship in the logo make sense or is that too on the nose?

**Comment by alerque** [comment]
I don't mind the use of a literal ship at all, in a lot of ways it makes sense. We don't *have to* go that way, but I don't think it's a problem if we come up with something different enough from Docker to avoid conflation.

For the square / round layout I do think this can be a reduction from whatever full logo / emblem we come up with and doesn't have to have all the detail or even the name. For example PyPi (yet another container stacking theme) reduces their logo progressively like this:

![image](https://user-images.githubusercontent.com/173595/90718651-1e19f200-e2bb-11ea-9382-31720f4a9cc2.png)

----

Non-designer throwing out ideas here: what about something with a ship's prow instead of the whole ship, perhaps more on the historical sailing ship than end of boat design than the modern container barge look, with "font"‌ or "fontship" emblazoned in some League font on the side? Perhaps rotated so the ship is pointed closer towards the viewer rather getting the profile.

**Comment by sprngr** [comment]
Good thoughts all around. I'll try to put some vectors together when I get some free moments this coming week.

**Comment by alerque** [comment]
Just bumped into [Codeship](https://codeship.com/about). I'm pretty sure they yanked my concepts.

**Comment by alerque** [comment]
This is cheating, but I wanted to see what it would look like:

![image](https://user-images.githubusercontent.com/173595/90866184-301f9180-e39c-11ea-944c-b912d3b4e92f.png)

**Comment by sprngr** [comment]
Had a few free cycles this weekend and put together a quick draft of something to break out of the literal ship idea, still going to tinker with making a bow of a ship though just wanting to throw out some more ideas to get things churning since I don't want this to clash with Codeship now.

Thought, why not bring another method of shipping into play:

![fontship_truck](https://user-images.githubusercontent.com/29021/90985007-e3c48500-e546-11ea-8423-72097e6d5b3f.png)

Going to look at some photos of boats and put together some ideas from that as well.

**Comment by alerque** [comment]
Hmmm. That's interesting too.

By chance while working on another project that runs in GitHub Actions, I ran into this:

![truck](https://feathericons.com/8901f5fe-158f-4913-8471-641047ccfd89)

What is that you ask? It's the [truck icon from Feather icons](https://feathericons.com/?query=truck). Of course we don't have to match anything that's in there exactly, but one place Actions lets us pick branding we have to pick one of those icons to go with our project. I currently have the [`package`](https://feathericons.com/?query=package) selected for Fontship, but the truck would fit the bill too!

**Comment by sprngr** [comment]
Hey, sorry for the long delay - was tied up with prior commitments and can now get back to this.

I actually do like the feather truck icon a bit, I'm going to work on variations inspired by that so it can feel consistent across the board.

**Comment by sprngr** [comment]
I tried to drive further (pun not intended) with the box truck concept. It felt sort of like fate given Feather Icons had a truck of their own.

I put together a few variations with open and filled boxes, as well as Regular and Italicised "F" glyphs written in Fanwood. I had tried to use the whole word "font" but it does not scale well in a vector that needs to fit a square aspect ratio.

I was kind of partial to the italic F on the truck as it kind of felt like it gave a bit of feel in direction or movement forward.

Looking forward to hearing your thoughts on this one.

![fontship_v2](https://user-images.githubusercontent.com/29021/93004709-acc70b00-f517-11ea-8179-10870b6f7d19.png)

**Comment by alerque** [comment]
I think something along those lines may be workable. Maybe without the F in the truck for the variants that have the full name? Perhaps also the baseline of the full name should align with the truck bed, not the F? But these are small details, I think we can probably run with the concept for now.

How about opening a PR with SVG or whatever vector graphics you have so far (or ever a couple iterations if you have any commit history for them). We can play with it a bit more and figure out how to break down what resources we need and where to put them.

**Comment by alerque** [comment]
Closed by #82. Many thanks @sprngr!

I'm still open to tweaks (as evidenced by #90) but this made it into the v0.5.0 release.
